version: '3.8'
services:
  
  postgres:
    container_name: postgr
    image: postgres:15.1-alpine
    environment:
        POSTGRES_DB: "fastapi_database"
        POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"

  scraper:
    container_name: scraper
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "python", "scraper.py"]
    
  webservice:
    container_name: webservice
    build:
      context: .
      dockerfile: ./webservice/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - scraper
    command: ["./wait-for-it.sh", "postgres:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]